# Generated by Django 2.2.10 on 2021-11-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211113_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
