# Generated by Django 2.2.10 on 2021-11-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='polls.Question')),
            ],
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
