# Generated by Django 2.2.10 on 2021-11-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20211113_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='e_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='polls',
            name='s_date',
            field=models.DateTimeField(),
        ),
    ]
