# Generated by Django 2.2.10 on 2021-11-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20211113_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.CharField(default=None, max_length=55),
        ),
    ]
